<?php

namespace PI\Premium_ImmobilierBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    public function listBien(){
    $qb = $this
    ->createQueryBuilder('b')
    ->leftJoin('b.images', 'img')
    ->addSelect('img');
    return $qb
    ->getQuery()
    ->getResult();
}

 public function findTypeBudjetLocalite($localite,$type){
    $qb = $this
    ->createQueryBuilder('b')
    ->leftJoin('b.Localite', 'loc')
    ->addSelect('loc')
    ->leftJoin('b.TypeBien','typ')
    ->addSelect('typ')
    ->where('b.Localite = :localite')
    ->setParameter('localite',$localite)
    ->andWhere('b.TypeBien= :type')
    ->setParameter('type',$type);

   
    return $qb
    ->getQuery()
    ->getResult();
}
}
